version: '3'
services:
  server:
    build: D:\GitHub\highloadserv\server
    ports:
      - "8080:80"
  clientcomponent:
    build: D:\GitHub\highloadserv\clientcomponent
    network_mode: host
    tty: true
    stdin_open: true
    
  redis-master:
    image: redis-master
    container_name: redis-master
    ports:
      - "6380:6380"
    networks:
      redis-replication:
        ipv4_address: 172.28.0.2
    command: redis-server /etc/redis.conf
    volumes: 
    - D:\GitHub\highloadserv\clientcomponent\config\redis-master.conf:/etc/redis.conf

  redis-replica-0:
    image: redis-replica-0
    container_name: redis-replica-0
    ports:
      - "6381:6380"
    command: redis-server /etc/redis.conf
    depends_on:
      - redis-master
    volumes:
      - D:\GitHub\highloadserv\clientcomponent\config\redis-replica-0.conf:/etc/redis.conf
    networks:
      redis-replication:
        ipv4_address: 172.28.0.3


  redis-replica-1:
    image: redis-replica-1
    container_name: redis-replica-1
    ports:
      - "6382:6380"
    command: redis-server /etc/redis.conf
    depends_on:
      - redis-master
    volumes:
      - D:\GitHub\highloadserv\clientcomponent\config\redis-replica-1.conf:/etc/redis.conf
    networks:
      redis-replication:
        ipv4_address: 172.28.0.4
        
networks:
  redis-replication:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16




